// Windows background service, via Task Scheduler.
//
// Why a scheduled task and not a real Windows Service: the collectors read
// %USERPROFILE%\.claude, \.codex, \.kimi-code. A service runs as SYSTEM, whose
// profile is C:\Windows\System32\config\systemprofile — every source would
// come up empty. Task Scheduler runs in the user's own session, needs no
// elevation, and the combination below reproduces the KeepAlive semantics
// launchd and systemd give us elsewhere.
//
// Reproducing KeepAlive takes three cooperating pieces, each covering a way
// the agent dies:
//   * RestartOnFailure     — crashes (non-zero exit).
//   * A repeating trigger  — clean exits. RestartOnFailure ignores exit 0, and
//     the logon trigger alone leaves a Ctrl+C'd agent dead until the next
//     sign-in, which on an always-on machine is unbounded. (Not hypothetical:
//     an agent died this way in the field and stayed down for days while its
//     WSL sibling on the same hardware heartbeated on.) The trigger re-fires
//     every 15 minutes; IgnoreNew makes each fire a no-op while alive.
//   * A wscript launcher   — the user. Task Scheduler shows a console window
//     for console programs in the interactive session, and a visible window
//     invites closing it. wscript starts node with no window at all.

import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, rmSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { saveProxyEnv } from "@/cli/proxy-env";

export const TASK_NAME = "Tokenizer Agent";

// How often the revive trigger re-fires. A fire while the agent is alive is
// swallowed by MultipleInstancesPolicy=IgnoreNew, so the interval only bounds
// how long a killed agent stays down.
const REVIVE_INTERVAL = "PT15M";
// Repetition is computed forward from this instant; any past date works.
// Fixed rather than "now" so the generated XML is deterministic.
const REVIVE_START_BOUNDARY = "2020-01-01T00:00:00";

export type AgentCommandOptions = {
  nodePath: string;
  scriptPath: string;
  heartbeatSeconds: number;
  syncMinutes: number;
};

export type TaskOptions = {
  wscriptPath: string;
  vbsPath: string;
  workingDir: string;
  userId?: string | null;
};

function escapeXml(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

// A literal quote inside a VBScript string is written as "".
function vbsString(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

export function currentTaskUser(): string | null {
  const user = process.env.USERNAME;
  if (!user) return null;
  const domain = process.env.USERDOMAIN;
  return domain ? `${domain}\\${user}` : user;
}

/**
 * Build the hidden launcher the scheduled task actually executes.
 *
 * Window style 0 starts node with no console window. The True (wait) flag is
 * load-bearing: wscript stays alive as the task's own process for as long as
 * node runs, so Task Scheduler still observes the agent's lifetime —
 * RestartOnFailure sees a crash through the propagated exit code, and the
 * revive trigger's IgnoreNew policy sees a live instance to skip. A
 * fire-and-forget launcher would instead read "completed" a second after
 * every start and spawn a fresh agent on every revive fire.
 */
export function buildAgentVbs(options: AgentCommandOptions): string {
  const command =
    `"${options.nodePath}" --import tsx "${options.scriptPath}" agent ` +
    `--heartbeat-seconds ${options.heartbeatSeconds} --sync-minutes ${options.syncMinutes}`;
  return [
    "' Tokenizer agent launcher — starts the agent with no console window.",
    "' Generated by `tokenizer install-service`; regenerated on every install.",
    "Dim shell, exitCode",
    'Set shell = CreateObject("WScript.Shell")',
    `exitCode = shell.Run(${vbsString(command)}, 0, True)`,
    "WScript.Quit exitCode",
    ""
  ].join("\r\n");
}

/**
 * Build the task definition.
 *
 * Four Task Scheduler defaults are actively hostile to a long-lived process
 * and are each overridden below. Left alone, the agent looks installed and
 * then quietly dies:
 *   ExecutionTimeLimit        default PT72H  — killed after three days
 *   StopIfGoingOnBatteries    default true   — killed the moment a laptop unplugs
 *   DisallowStartIfOnBatteries default true  — never starts on battery at all
 *   StopOnIdleEnd             default true   — killed when the machine leaves idle
 *
 * Element order inside <Settings> is schema-significant: this is the sequence
 * Task Scheduler itself emits when exporting a task. Same for the trigger
 * elements (Repetition before StartBoundary before Enabled).
 */
export function buildTaskXml(options: TaskOptions): string {
  const args = `//B //Nologo "${options.vbsPath}"`;

  // `??` would be wrong here: an explicit null means "register without a
  // UserId", and `??` cannot distinguish that from the property being absent.
  const userId = options.userId !== undefined ? options.userId : currentTaskUser();
  const triggerUser = userId ? `\n      <UserId>${escapeXml(userId)}</UserId>` : "";
  const principalUser = userId ? `\n      <UserId>${escapeXml(userId)}</UserId>` : "";

  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>Tokenizer usage collection agent</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>${triggerUser}
    </LogonTrigger>
    <TimeTrigger>
      <Repetition>
        <Interval>${REVIVE_INTERVAL}</Interval>
        <StopAtDurationEnd>false</StopAtDurationEnd>
      </Repetition>
      <StartBoundary>${REVIVE_START_BOUNDARY}</StartBoundary>
      <Enabled>true</Enabled>
    </TimeTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">${principalUser}
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>
    <IdleSettings>
      <StopOnIdleEnd>false</StopOnIdleEnd>
      <RestartOnIdle>false</RestartOnIdle>
    </IdleSettings>
    <AllowStartOnDemand>true</AllowStartOnDemand>
    <Enabled>true</Enabled>
    <Hidden>false</Hidden>
    <RunOnlyIfIdle>false</RunOnlyIfIdle>
    <WakeToRun>false</WakeToRun>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <Priority>7</Priority>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>999</Count>
    </RestartOnFailure>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>${escapeXml(options.wscriptPath)}</Command>
      <Arguments>${escapeXml(args)}</Arguments>
      <WorkingDirectory>${escapeXml(options.workingDir)}</WorkingDirectory>
    </Exec>
  </Actions>
</Task>
`;
}

/**
 * schtasks rejects a UTF-8 XML file with a bare "task XML is malformed" — it
 * expects UTF-16, detected via the BOM. The same encoding serves the .vbs
 * launcher: its command line embeds the install path, which contains the
 * username and may be non-ASCII; an ANSI-encoded .vbs would corrupt it, and
 * WSH reads UTF-16 sources from the BOM just like schtasks does.
 */
export function encodeUtf16Le(text: string): Buffer {
  return Buffer.from(`﻿${text}`, "utf16le");
}

export function registerTask(xml: string, taskName = TASK_NAME): void {
  const file = join(tmpdir(), `tokenizer-task-${process.pid}.xml`);
  writeFileSync(file, encodeUtf16Le(xml));
  try {
    execFileSync("schtasks", ["/Create", "/TN", taskName, "/XML", file, "/F"], { stdio: "inherit" });
  } finally {
    rmSync(file, { force: true });
  }
}

function agentVbsPath(): string {
  return join(homedir(), ".tokenizer", "bin", "tokenizer-agent.vbs");
}

export function installWindowsService(options: { heartbeatSeconds: number; syncMinutes: number }, installRoot: string): string {
  const vbsPath = agentVbsPath();
  mkdirSync(join(homedir(), ".tokenizer", "bin"), { recursive: true });
  const vbs = buildAgentVbs({
    // process.execPath is the absolute node.exe currently running us, which
    // sidesteps Task Scheduler's PATH being different from the user's shell.
    nodePath: process.execPath,
    scriptPath: join(installRoot, "src", "cli", "index.ts"),
    heartbeatSeconds: options.heartbeatSeconds,
    syncMinutes: options.syncMinutes
  });
  writeFileSync(vbsPath, encodeUtf16Le(vbs));

  const xml = buildTaskXml({
    wscriptPath: join(process.env.SystemRoot ?? "C:\\Windows", "System32", "wscript.exe"),
    vbsPath,
    // tsx is resolved relative to the working directory (same reason
    // bin/tokenizer sets cwd); wscript's child inherits it.
    workingDir: installRoot
  });
  registerTask(xml);
  // A task definition cannot carry environment variables, so the proxy
  // settings from the installing shell are snapshotted to disk instead.
  const proxy = saveProxyEnv();
  const proxyKeys = Object.keys(proxy);
  const logPath = join(homedir(), ".tokenizer", "logs", "agent.log");
  const proxyLine = proxyKeys.length ? `\nproxy env saved: ${proxyKeys.join(", ")}` : "";
  return `Installed scheduled task: ${TASK_NAME}\nRuns hidden in the background; restarts on crash, revives within 15 minutes of any exit.\nLog: ${logPath}${proxyLine}`;
}

export function uninstallWindowsService(): string | null {
  // Launcher first: if the task is already gone (partial uninstall, manual
  // deletion) the schtasks call throws, and an orphaned .vbs must not survive
  // behind it.
  rmSync(agentVbsPath(), { force: true });
  try {
    execFileSync("schtasks", ["/Delete", "/TN", TASK_NAME, "/F"], { stdio: "ignore" });
    return `Removed scheduled task: ${TASK_NAME}`;
  } catch {
    return null;
  }
}

export function windowsServiceStatus(): string | null {
  try {
    const output = execFileSync("schtasks", ["/Query", "/TN", TASK_NAME, "/FO", "LIST"], {
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"]
    });
    const status = /^\s*Status:\s*(.+)$/m.exec(output)?.[1]?.trim();
    return `schtasks: ${TASK_NAME}${status ? ` (${status})` : ""}`;
  } catch {
    return null;
  }
}
