// Public list-price catalog for cost estimation. Prices are USD per 1M tokens,
// captured from each vendor's official pricing page on 2026-05-17. Source URLs
// are attached per entry so the next person editing this file can re-verify.
//
// Token semantics in this codebase:
//   inputTokens   = total input the model saw, includes cachedInputTokens and
//                   cacheWriteTokens as subsets
//   cachedInputTokens = portion served from cache (cheap)
//   cacheWriteTokens  = portion freshly written to cache (charged separately;
//                       Anthropic charges a 1.25x premium, others bill at base
//                       input rate so cacheWrite == input)
//   outputTokens  = generated by the model
//
// "Fresh input" (charged at the base input rate) is therefore
//   max(0, inputTokens - cachedInputTokens - cacheWriteTokens)

export type ModelPriceRow = {
  input: number;
  cacheRead: number;
  cacheWrite: number;
  output: number;
};

export const MODEL_PRICES: Record<string, ModelPriceRow> = {
  // Anthropic — https://platform.claude.com/docs/en/about-claude/pricing
  // Cache write = 1.25x base input (5-minute cache), cache read = 0.1x base input.
  "claude-opus-4-7": { input: 5.0, cacheRead: 0.5, cacheWrite: 6.25, output: 25.0 },
  "claude-opus-4-6": { input: 5.0, cacheRead: 0.5, cacheWrite: 6.25, output: 25.0 },
  "claude-sonnet-4-6": { input: 3.0, cacheRead: 0.3, cacheWrite: 3.75, output: 15.0 },
  "claude-haiku-4-5": { input: 1.0, cacheRead: 0.1, cacheWrite: 1.25, output: 5.0 },

  // OpenAI — https://developers.openai.com/api/docs/pricing (verified 2026-05-17)
  // OpenAI exposes a cache-read discount only; first writes are billed at the
  // base input rate (no explicit cache-write premium), so cacheWrite == input.
  "gpt-5.5": { input: 5.0, cacheRead: 0.5, cacheWrite: 5.0, output: 30.0 },
  "gpt-5.4": { input: 2.5, cacheRead: 0.25, cacheWrite: 2.5, output: 15.0 },
  "gpt-5.4-mini": { input: 0.75, cacheRead: 0.075, cacheWrite: 0.75, output: 4.5 },

  // OpenAI Codex variants — https://developers.openai.com/codex/pricing
  // The Codex page lists prices in credits at 25 credits = $1; e.g. gpt-5.3-codex
  // is 43.75 / 4.375 / 350 credits ≈ $1.75 / $0.175 / $14 / Mtok.
  "gpt-5.3-codex": { input: 1.75, cacheRead: 0.175, cacheWrite: 1.75, output: 14.0 },
  // gpt-5.1-codex follows the older GPT-5.1 rate card (no Codex premium for the
  // 5.1 generation per helicone.ai's verified table); cacheRead defaults to
  // base input since OpenAI didn't document a cached-discount line.
  "gpt-5.1-codex": { input: 1.25, cacheRead: 0.125, cacheWrite: 1.25, output: 10.0 },
  "gpt-5.1-codex-mini": { input: 0.25, cacheRead: 0.025, cacheWrite: 0.25, output: 2.0 },

  // Google AI — https://ai.google.dev/gemini-api/docs/pricing
  // Pricing below 200K context; above 200K input/output bumps to $4 / $18 — out
  // of scope for the initial table, revisit if long-context usage shows up.
  "gemini-3.1-pro-preview": { input: 2.0, cacheRead: 0.2, cacheWrite: 2.0, output: 12.0 },

  // MiniMax M2.5 accessed via OpenRouter free tier — the "-free" suffix in the
  // model id means literal $0 to the user. The paid tier (minimax-m2.5 without
  // -free) lists at $0.30 / $1.20 per Mtok; add it if we see paid traffic.
  "minimax-m2.5-free": { input: 0, cacheRead: 0, cacheWrite: 0, output: 0 }
};

// Xiaomi MiMo is omitted from MODEL_PRICES because its pricing structure
// has no native cache pricing exposed. Mapped to base-rate by aliasing the
// official key.
MODEL_PRICES["mimo-v2.5-pro"] = { input: 1.0, cacheRead: 1.0, cacheWrite: 1.0, output: 3.0 };

const DATE_SUFFIX_RE = /-\d{8}$/;

// Some providers append a build date to the model string (e.g.
// claude-haiku-4-5-20251001). The pricing table is keyed without the suffix
// so user-facing dashboards stay stable across model refreshes.
export function normalizeModelKey(model: string | null | undefined): string | null {
  if (!model) return null;
  return model.toLowerCase().trim().replace(DATE_SUFFIX_RE, "");
}

export type TokenAggregate = {
  inputTokens: number;
  cachedInputTokens: number;
  cacheWriteTokens: number;
  outputTokens: number;
};

// Returns USD cost or null when the model is unknown / unpriced. Callers
// decide whether to surface "—" or fall back to 0; we deliberately do not
// silently bill unknown models at $0 so the data-quality story stays visible.
export function estimateCost(model: string | null | undefined, t: TokenAggregate): number | null {
  const key = normalizeModelKey(model);
  if (!key) return null;
  const price = MODEL_PRICES[key];
  if (!price) return null;
  const fresh = Math.max(0, t.inputTokens - t.cachedInputTokens - t.cacheWriteTokens);
  return (
    (fresh * price.input) / 1_000_000 +
    (t.cachedInputTokens * price.cacheRead) / 1_000_000 +
    (t.cacheWriteTokens * price.cacheWrite) / 1_000_000 +
    (t.outputTokens * price.output) / 1_000_000
  );
}

// Reduce a list of (model, tokens) aggregate rows to a single USD total. Rows
// for unknown models contribute 0 but their token counts are returned via
// `unpricedTokens` so callers can surface the gap if they want to.
export function sumCostAcrossModels(
  rows: Array<{ model: string | null | undefined } & TokenAggregate>
): { cost: number; unpricedTokens: number } {
  let cost = 0;
  let unpricedTokens = 0;
  for (const row of rows) {
    const c = estimateCost(row.model, row);
    if (c == null) {
      unpricedTokens += row.inputTokens + row.outputTokens;
    } else {
      cost += c;
    }
  }
  return { cost, unpricedTokens };
}
