"use client";

import { useEffect, useState } from "react";
import { MdContentCopy, MdCheckCircle, MdAccessTime, MdRefresh } from "react-icons/md";
import {
  enrollmentPollDelayMs,
  isEnrollmentClaimed,
  type EnrollmentStatus
} from "@/shared/enrollment-status";

type Mode = "idle" | "generating" | "waiting" | "success" | "error";

type ResponseDevice = { deviceId: string; name: string };

const POLL_MAX_MS = 10 * 60 * 1000; // stop polling after 10 minutes — token also expires before then

// Self-contained enrollment flow: click "生成命令" → server returns a one-time
// curl line → component polls that enrollment until it is claimed. This binds
// success to the command generated here rather than to any newly seen device.
export function EnrollFlowCard({
  onSuccess
}: {
  onSuccess?: (device: ResponseDevice) => void;
}) {
  const [mode, setMode] = useState<Mode>("idle");
  // Both platform variants are kept so a Windows user is not handed a bash
  // one-liner; `platform` selects which one is shown and copied.
  const [commands, setCommands] = useState<{ id: string; label: string; command: string }[]>([]);
  const [platform, setPlatform] = useState<string | null>(null);
  const [expiresAt, setExpiresAt] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [newDevice, setNewDevice] = useState<ResponseDevice | null>(null);
  const [secondsLeft, setSecondsLeft] = useState<number | null>(null);
  const [enrollmentId, setEnrollmentId] = useState<string | null>(null);

  async function generate() {
    setMode("generating");
    setError(null);
    setCommands([]);
    setNewDevice(null);
    setEnrollmentId(null);
    try {
      const response = await fetch("/api/admin/enrollment-tokens", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ expiresInMinutes: 30 })
      });
      const json = await response.json();
      if (!response.ok) throw new Error(json.error || "failed to generate install command");
      if (typeof json.enrollmentId !== "string" || json.enrollmentId.length === 0) {
        throw new Error("failed to create enrollment status");
      }
      setCommands(
        json.installCommands ?? [{ id: "posix", label: "macOS / Linux", command: json.installCommand }]
      );
      setExpiresAt(json.expiresAt);
      setEnrollmentId(json.enrollmentId);
      setMode("waiting");
    } catch (err) {
      setError(err instanceof Error ? err.message : String(err));
      setMode("error");
    }
  }

  const activeCommand = commands.find((entry) => entry.id === platform) ?? commands[0] ?? null;

  async function copyCommand() {
    if (!activeCommand) return;
    try {
      await navigator.clipboard.writeText(activeCommand.command);
      setCopied(true);
      setTimeout(() => setCopied(false), 2_000);
    } catch {
      /* clipboard may be unavailable on http or older browsers */
    }
  }

  // Poll only the token generated by this flow. Each transient miss backs off,
  // and cleanup aborts both the active request and the next scheduled tick.
  useEffect(() => {
    if (mode !== "waiting" || !enrollmentId) return;
    let cancelled = false;
    let timeoutId: ReturnType<typeof setTimeout> | null = null;
    const controller = new AbortController();
    const start = Date.now();
    let attempt = 0;
    const tick = async () => {
      if (cancelled) return;
      try {
        const response = await fetch(`/api/admin/enrollment-tokens/${encodeURIComponent(enrollmentId)}`, {
          cache: "no-store",
          signal: controller.signal
        });
        if (response.ok) {
          const status = (await response.json()) as EnrollmentStatus;
          if (isEnrollmentClaimed(status) && status.deviceName && !cancelled) {
            const device = { deviceId: status.usedById!, name: status.deviceName };
            setNewDevice(device);
            setMode("success");
            onSuccess?.(device);
            return;
          }
        }
      } catch (err) {
        if (err instanceof DOMException && err.name === "AbortError") return;
        if (controller.signal.aborted) return;
        /* transient network blip — keep polling */
      }
      if (cancelled) return;
      if (Date.now() - start >= POLL_MAX_MS) {
        setError("超时,未检测到新设备。请确认终端命令已成功运行,或重新生成命令。");
        setMode("error");
        return;
      }
      timeoutId = setTimeout(tick, enrollmentPollDelayMs(attempt));
      attempt += 1;
    };
    void tick();
    return () => {
      cancelled = true;
      controller.abort();
      if (timeoutId) clearTimeout(timeoutId);
    };
  }, [mode, enrollmentId, onSuccess]);

  // Show a live countdown for the token-expires hint
  useEffect(() => {
    if (mode !== "waiting" || !expiresAt) return;
    const expiry = new Date(expiresAt).getTime();
    const tick = () => {
      const remaining = Math.max(0, Math.floor((expiry - Date.now()) / 1000));
      setSecondsLeft(remaining);
    };
    tick();
    const id = setInterval(tick, 1_000);
    return () => clearInterval(id);
  }, [mode, expiresAt]);

  if (mode === "success" && newDevice) {
    return (
      <div className="rounded-2xl border border-emerald-200 bg-emerald-50/60 p-6 dark:border-emerald-400/30 dark:bg-emerald-500/10">
        <div className="flex items-start gap-3">
          <span className="rounded-full bg-emerald-500/15 p-2 text-emerald-600 dark:text-emerald-300">
            <MdCheckCircle className="h-6 w-6" />
          </span>
          <div className="flex-1">
            <h3 className="text-base font-bold text-emerald-700 dark:text-emerald-300">已连接:{newDevice.name}</h3>
            <p className="mt-1 text-sm text-emerald-700/80 dark:text-emerald-200/70">
              客户端在线。首次同步需要 60-90 秒,数据会自动出现在 dashboard 上。
            </p>
            <div className="mt-4 flex gap-2">
              <button
                onClick={() => {
                  setMode("idle");
                  setCommands([]);
                  setNewDevice(null);
                  setEnrollmentId(null);
                  setError(null);
                }}
                className="inline-flex items-center gap-1 rounded-lg border border-emerald-300 bg-white px-3 py-1.5 text-xs font-medium text-emerald-700 transition hover:bg-emerald-50 dark:border-emerald-400/30 dark:bg-navy-800 dark:text-emerald-300 dark:hover:bg-emerald-500/10"
              >
                <MdRefresh className="h-3.5 w-3.5" />
                继续添加另一台
              </button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div>
      {mode === "idle" || mode === "error" ? (
        <button
          onClick={generate}
          className="inline-flex items-center gap-2 rounded-xl bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-brand-600 active:scale-[0.99]"
        >
          生成安装命令
        </button>
      ) : null}
      {mode === "generating" ? (
        <button disabled className="inline-flex items-center gap-2 rounded-xl bg-brand-500/60 px-4 py-2.5 text-sm font-semibold text-white">
          正在生成...
        </button>
      ) : null}

      {error ? (
        <div className="mt-3 rounded-xl border border-red-200 bg-red-50 px-3 py-2 text-sm text-red-700 dark:border-red-500/30 dark:bg-red-500/10 dark:text-red-300">
          {error}
        </div>
      ) : null}

      {activeCommand && (mode === "waiting" || mode === "error") ? (
        <div className="mt-4 space-y-3">
          <div className="rounded-xl border border-gray-200 bg-gray-50 p-4 dark:border-white/10 dark:bg-navy-900/60">
            <div className="flex items-center justify-between gap-2">
              <div className="flex items-center gap-1.5 text-xs text-gray-500">
                <MdAccessTime className="h-3.5 w-3.5" />
                <span>
                  有效期 {secondsLeft != null ? formatSeconds(secondsLeft) : "30 分钟"} {secondsLeft != null && secondsLeft <= 0 ? "(已过期,请重新生成)" : ""}
                </span>
              </div>
              <button
                onClick={copyCommand}
                className="inline-flex items-center gap-1 rounded-lg border border-gray-300 bg-white px-2 py-1 text-xs font-medium text-gray-700 transition hover:bg-gray-50 dark:border-white/10 dark:bg-navy-800 dark:text-gray-200 dark:hover:bg-white/5"
              >
                {copied ? <MdCheckCircle className="h-3.5 w-3.5 text-emerald-500" /> : <MdContentCopy className="h-3.5 w-3.5" />}
                {copied ? "已复制" : "复制"}
              </button>
            </div>
            <div className="mt-2 flex items-center gap-1">
                    {commands.length > 1
                      ? commands.map((entry) => (
                          <button
                            key={entry.id}
                            type="button"
                            onClick={() => setPlatform(entry.id)}
                            className={`rounded-md px-2 py-0.5 text-xs font-medium ${
                              entry.id === activeCommand.id
                                ? "bg-gray-100 text-navy-700 dark:bg-white/10 dark:text-gray-100"
                                : "text-gray-500 dark:text-gray-400"
                            }`}
                          >
                            {entry.label}
                          </button>
                        ))
                      : null}
                  </div>
                  <pre className="mt-2 overflow-x-auto whitespace-pre-wrap break-all font-mono text-sm text-brand-500 dark:text-brand-300">{activeCommand.command}</pre>
          </div>
          {mode === "waiting" ? (
            <div className="flex items-center gap-2 text-sm text-gray-600 dark:text-gray-400">
              <span className="inline-flex h-2 w-2 animate-pulse rounded-full bg-brand-500" />
              <span>等待客户端首次上线... 一旦连接成功这里会自动显示。</span>
            </div>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}

function formatSeconds(s: number): string {
  if (s <= 0) return "0 秒";
  const m = Math.floor(s / 60);
  const r = s % 60;
  if (m > 0) return `${m} 分 ${r} 秒`;
  return `${r} 秒`;
}
